spring:
  datasource:
    url: jdbc:h2:file:./pmdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /api/v1/auth/h2-console
token:
  signing:
    key: 4B28E7082C7773B592BB16CFE00B6EBA1F78BE98E61B3F1BF6BBD63F444F58C4

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/auth/swagger-ui
  api-docs.path: /api/v1/auth/api-docs